DROP DATABASE IF EXISTS quan_li_sinh_vien;
CREATE DATABASE  quan_li_sinh_vien;
USE  quan_li_sinh_vien;
CREATE TABLE class(
class_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
class_name VARCHAR(60) NOT NULL,
start_date DATETIME NOT NULL,
status BIT
);
CREATE TABLE student(
student_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
student_name VARCHAR(30) NOT NULL,
address VARCHAR(50),
phone VARCHAR(20),
status BIT,
class_ID int NOT NULL,
FOREIGN KEY (class_ID) REFERENCES class(class_ID)
);
CREATE TABLE subject(
sub_ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
sub_name VARCHAR (30) NOT NULL,
credit TINYINT NOT NULL DEFAULT 1 CHECK (credit >=1),
status BIT DEFAULT 1 
);
CREATE TABLE mark(
mark_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
sub_ID INT NOT NULL UNIQUE,
student_ID INT NOT NULL UNIQUE,
mark FLOAT DEFAULT 0 CHECK (mark BETWEEN 0 AND 100),
exame_time TINYINT DEFAULT 1,
FOREIGN KEY (sub_ID) REFERENCES subject(sub_ID),
FOREIGN KEY (student_ID) REFERENCES student(student_ID)
);
